version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: waskita_db
    environment:
      POSTGRES_DB: waskita_prod
      POSTGRES_USER: waskita_user
      POSTGRES_PASSWORD: waskita_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - waskita_network
    restart: unless-stopped

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: waskita_redis
    ports:
      - "6379:6379"
    networks:
      - waskita_network
    restart: unless-stopped

  # Waskita Application
  web:
    build: .
    container_name: waskita_app
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://waskita_user:waskita_password@db:5432/waskita_prod
      - SECRET_KEY=your-production-secret-key-change-this
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./models:/app/models
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    networks:
      - waskita_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: waskita_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static
      - ./ssl:/etc/nginx/ssl  # For SSL certificates
    depends_on:
      - web
    networks:
      - waskita_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  waskita_network:
    driver: bridge